### ISSUE TITLE
Does it work without typing "get"?

### ISSUE THREAD

**Issue by KuenzelIT** [laercioskt/ulauncher-kv#1]
Hello there,

I like this extension very much since I use a similar extension in Albert (which does not seem to be supported anymore). In Albert I don't have to type "kv get", it gets the snippets directly. I assume this does not work with Ulauncher because of the required keyword, but can this extension work without typing "get"? It would make it a little smaller and easier to use e.g. "kv mykeyword".

I'm always trying to keep the strings short since I use these extensions a lot.

Thanks!

**Comment by laercioskt** [comment]
Hi @KuenzelIT 

I just saw your message and tried to implement what you want.

Can you test the change?

Note: There are other problems with this extension, when compared to Albert's KV, but that I will need to spend more time to solve them. Feel free to propose here and I will try to implement it.

Hope this helps.
