### ISSUE TITLE
Expode the DB path in the configuration and allow the user to overwrite it

### ISSUE THREAD

**Issue by rabin-io** [laercioskt/ulauncher-kv#2]
If you can please add support to config the DB path, and expose this in the configuration window.

https://github.com/laercioskt/ulauncher-kv/blob/348798a4588e0fb7a6590f399426d56b22a6f3fb/db.py#L5

**Comment by laercioskt** [comment]
Thank you for the suggestion.

I did it on commit https://github.com/laercioskt/ulauncher-kv/commit/5382d81035193309d281c52503cd05a8e8dd045d.

I appreciate any feedback.
See you.

**Comment by rabin-io** [comment]
Thanks. 

Now I can sync the file across devices :)
